### ISSUE TITLE
[proposal]L-SMASH-Works側でffmpeg更新に対応するpatchがmergeされたのでworkaroundのpatchを除去する

### ISSUE THREAD

**Issue by yumetodo** [MaverickTse/lsw-build3#3]
https://github.com/VFR-maniac/L-SMASH-Works/pull/75
をrebaseしたと思われる
- https://github.com/VFR-maniac/L-SMASH-Works/commit/fde7a685bb56d05a657b837e4c40dedc8d87949a
- https://github.com/VFR-maniac/L-SMASH-Works/commit/4c10d790e664c526d57c4070061ade67b2dfdee0
- https://github.com/VFR-maniac/L-SMASH-Works/commit/cd1daf032e04994f095dc6497b66d906045a4b3b

がmasterにcommit されている。

つまり
https://github.com/MaverickTse/lsw-build3/blob/e84646d66e02a0bc2bfbed0b1ce25bb6deed9035/LSWAviUtl_input_buffer_padding_size_20180220.patch
は不要になったのではないかと思われる。

Todo:
- [ ] 実際にビルドしてみる

**Comment by MaverickTse** [comment]
Travisで問題なし確認したので、mergeに行きます
https://travis-ci.org/MaverickTse/LSW-AutoCIBuild/builds/360277560?utm_source=github_status&utm_medium=notification

**Comment by MaverickTse** [comment]
Merged　https://github.com/MaverickTse/lsw-build3/pull/4
